services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.app
    environment:
      - YOLO_URL=http://yolo:5001
      - TENSORFLOW_URL=http://tensorflow:5002
      - CLIP_URL=http://clip:5003
    ports:
      - "5000:5000"
    networks:
      - backend  # 🔹 Сеть "backend"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    environment:
      - REACT_APP_API_URL=http://app:5000
    ports:
      - "3000:3000"
    networks:
      - backend  # 🔹 Сеть "backend"

networks:
  backend:
    driver: bridge  # 🔹 Добавили сеть "backend"
