version: "3.8"

services:
  yolo:
    build: ./yolo
    ports:
      - "5001:5001"
    restart: always

  tensorflow:
    build: ./tensorflow
    ports:
      - "5002:5002"
    restart: always

  clip:
    build: ./clip
    ports:
      - "5003:5003"
    restart: always

  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - yolo
      - tensorflow
      - clip
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    environment:
      - REACT_APP_API_URL=http://app:5000
    ports:
      - "3000:3000"
    networks:
      - backend  # 🔹 Сеть "backend"

networks:
  backend:
    driver: bridge  # 🔹 Добавили сеть "backend"
